-- NexSupply Database Schema
-- Required 19-table design from NexSupply-Database-Schema.pdf
-- PostgreSQL
-- Schema only: no project/sample data is inserted.

BEGIN;

-- 1. MASTER DATA

CREATE TABLE products (
    product_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_name VARCHAR(255) NOT NULL,
    category VARCHAR(100),
    description TEXT
);

CREATE TABLE locations (
    location_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location_name VARCHAR(255) NOT NULL,
    location_type VARCHAR(50) NOT NULL,
    city VARCHAR(100),
    country VARCHAR(100)
);

CREATE TABLE skus (
    sku_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id INTEGER NOT NULL,
    sku_code VARCHAR(100) NOT NULL UNIQUE,
    description TEXT,
    size VARCHAR(50),
    color VARCHAR(50),
    CONSTRAINT fk_skus_product FOREIGN KEY (product_id)
        REFERENCES products(product_id) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE suppliers (
    supplier_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_name VARCHAR(255) NOT NULL,
    location_id INTEGER,
    contact_info VARCHAR(255),
    lead_time_days INTEGER,
    moq INTEGER,
    CONSTRAINT fk_suppliers_location FOREIGN KEY (location_id)
        REFERENCES locations(location_id) ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT chk_suppliers_lead_time CHECK (lead_time_days IS NULL OR lead_time_days >= 0),
    CONSTRAINT chk_suppliers_moq CHECK (moq IS NULL OR moq >= 0)
);

CREATE TABLE factories (
    factory_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    factory_name VARCHAR(255) NOT NULL,
    location_id INTEGER,
    production_capacity INTEGER,
    CONSTRAINT fk_factories_location FOREIGN KEY (location_id)
        REFERENCES locations(location_id) ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT chk_factories_capacity CHECK (production_capacity IS NULL OR production_capacity >= 0)
);

CREATE TABLE carriers (
    carrier_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    carrier_name VARCHAR(255) NOT NULL,
    contact_info VARCHAR(255)
);

-- 2. P2 PLANNING

CREATE TABLE demand_forecast (
    forecast_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku_id INTEGER NOT NULL,
    location_id INTEGER NOT NULL,
    forecast_date DATE NOT NULL,
    forecast_quantity INTEGER NOT NULL,
    actual_quantity INTEGER,
    forecast_method VARCHAR(100),
    confidence_score DECIMAL(5,4),
    CONSTRAINT fk_forecast_sku FOREIGN KEY (sku_id)
        REFERENCES skus(sku_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_forecast_location FOREIGN KEY (location_id)
        REFERENCES locations(location_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT chk_forecast_quantity CHECK (forecast_quantity >= 0),
    CONSTRAINT chk_actual_quantity CHECK (actual_quantity IS NULL OR actual_quantity >= 0),
    CONSTRAINT chk_confidence_score CHECK (
        confidence_score IS NULL OR (confidence_score >= 0 AND confidence_score <= 1)
    )
);

CREATE TABLE production_orders (
    production_order_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    factory_id INTEGER NOT NULL,
    sku_id INTEGER NOT NULL,
    planned_quantity INTEGER NOT NULL,
    planned_date DATE NOT NULL,
    status VARCHAR(50) NOT NULL,
    actual_quantity INTEGER,
    CONSTRAINT fk_production_factory FOREIGN KEY (factory_id)
        REFERENCES factories(factory_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_production_sku FOREIGN KEY (sku_id)
        REFERENCES skus(sku_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT chk_planned_quantity CHECK (planned_quantity >= 0),
    CONSTRAINT chk_actual_production_quantity CHECK (
        actual_quantity IS NULL OR actual_quantity >= 0
    )
);

CREATE TABLE inventory (
    inventory_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location_id INTEGER NOT NULL,
    sku_id INTEGER NOT NULL,
    quantity INTEGER NOT NULL,
    reserved_quantity INTEGER NOT NULL DEFAULT 0,
    inventory_date DATE NOT NULL,
    stock_status VARCHAR(50),
    CONSTRAINT fk_inventory_location FOREIGN KEY (location_id)
        REFERENCES locations(location_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_inventory_sku FOREIGN KEY (sku_id)
        REFERENCES skus(sku_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT chk_inventory_quantity CHECK (quantity >= 0),
    CONSTRAINT chk_reserved_quantity CHECK (
        reserved_quantity >= 0 AND reserved_quantity <= quantity
    )
);

CREATE TABLE fabric_procurement (
    procurement_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id INTEGER NOT NULL,
    factory_id INTEGER NOT NULL,
    material VARCHAR(255) NOT NULL,
    quantity INTEGER NOT NULL,
    required_date DATE NOT NULL,
    lead_time_days INTEGER,
    status VARCHAR(50) NOT NULL,
    CONSTRAINT fk_procurement_supplier FOREIGN KEY (supplier_id)
        REFERENCES suppliers(supplier_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_procurement_factory FOREIGN KEY (factory_id)
        REFERENCES factories(factory_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT chk_procurement_quantity CHECK (quantity >= 0),
    CONSTRAINT chk_procurement_lead_time CHECK (
        lead_time_days IS NULL OR lead_time_days >= 0
    )
);

-- 3. COMMON BRIDGE

CREATE TABLE shipments (
    shipment_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shipment_reference VARCHAR(100) NOT NULL UNIQUE,
    sku_id INTEGER NOT NULL,
    quantity INTEGER NOT NULL,
    origin_location_id INTEGER NOT NULL,
    destination_location_id INTEGER NOT NULL,
    planned_arrival TIMESTAMP NOT NULL,
    priority VARCHAR(50) NOT NULL,
    status VARCHAR(50) NOT NULL,
    CONSTRAINT fk_shipments_sku FOREIGN KEY (sku_id)
        REFERENCES skus(sku_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_shipments_origin FOREIGN KEY (origin_location_id)
        REFERENCES locations(location_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_shipments_destination FOREIGN KEY (destination_location_id)
        REFERENCES locations(location_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT chk_shipment_quantity CHECK (quantity > 0)
);

-- 4. E2 EXECUTION

CREATE TABLE trailers (
    trailer_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    carrier_id INTEGER NOT NULL,
    load_type VARCHAR(100),
    priority VARCHAR(50),
    status VARCHAR(50) NOT NULL,
    CONSTRAINT fk_trailers_carrier FOREIGN KEY (carrier_id)
        REFERENCES carriers(carrier_id) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE trucks (
    truck_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    carrier_id INTEGER NOT NULL,
    trailer_id INTEGER,
    shipment_id INTEGER,
    status VARCHAR(50) NOT NULL,
    CONSTRAINT fk_trucks_carrier FOREIGN KEY (carrier_id)
        REFERENCES carriers(carrier_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_trucks_trailer FOREIGN KEY (trailer_id)
        REFERENCES trailers(trailer_id) ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT fk_trucks_shipment FOREIGN KEY (shipment_id)
        REFERENCES shipments(shipment_id) ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE dock_doors (
    dock_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dock_number VARCHAR(100) NOT NULL UNIQUE,
    dock_type VARCHAR(100),
    capability VARCHAR(255),
    status VARCHAR(50) NOT NULL
);

CREATE TABLE yard_locations (
    yard_location_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location_name VARCHAR(255) NOT NULL,
    capacity INTEGER NOT NULL,
    occupancy INTEGER NOT NULL DEFAULT 0,
    status VARCHAR(50) NOT NULL,
    CONSTRAINT chk_yard_capacity CHECK (capacity >= 0),
    CONSTRAINT chk_yard_occupancy CHECK (occupancy >= 0 AND occupancy <= capacity)
);

CREATE TABLE appointments (
    appointment_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shipment_id INTEGER NOT NULL,
    truck_id INTEGER NOT NULL,
    dock_id INTEGER NOT NULL,
    scheduled_arrival TIMESTAMP NOT NULL,
    status VARCHAR(50) NOT NULL,
    CONSTRAINT fk_appointments_shipment FOREIGN KEY (shipment_id)
        REFERENCES shipments(shipment_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_appointments_truck FOREIGN KEY (truck_id)
        REFERENCES trucks(truck_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_appointments_dock FOREIGN KEY (dock_id)
        REFERENCES dock_doors(dock_id) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE truck_tracking (
    tracking_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    truck_id INTEGER NOT NULL,
    latitude DECIMAL(10,7) NOT NULL,
    longitude DECIMAL(10,7) NOT NULL,
    speed DECIMAL(10,2),
    eta TIMESTAMP,
    timestamp TIMESTAMP NOT NULL,
    CONSTRAINT fk_tracking_truck FOREIGN KEY (truck_id)
        REFERENCES trucks(truck_id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE dock_assignments (
    assignment_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    truck_id INTEGER NOT NULL,
    dock_id INTEGER NOT NULL,
    appointment_id INTEGER,
    assigned_time TIMESTAMP NOT NULL,
    status VARCHAR(50) NOT NULL,
    reason TEXT,
    recommended_dock INTEGER,
    recommendation_reason TEXT,
    alternative_dock INTEGER,
    CONSTRAINT fk_assignments_truck FOREIGN KEY (truck_id)
        REFERENCES trucks(truck_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_assignments_dock FOREIGN KEY (dock_id)
        REFERENCES dock_doors(dock_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_assignments_appointment FOREIGN KEY (appointment_id)
        REFERENCES appointments(appointment_id) ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT fk_assignments_recommended_dock FOREIGN KEY (recommended_dock)
        REFERENCES dock_doors(dock_id) ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT fk_assignments_alternative_dock FOREIGN KEY (alternative_dock)
        REFERENCES dock_doors(dock_id) ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE alerts (
    alert_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alert_type VARCHAR(100) NOT NULL,
    truck_id INTEGER,
    shipment_id INTEGER,
    dock_id INTEGER,
    message TEXT NOT NULL,
    severity VARCHAR(50) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    status VARCHAR(50) NOT NULL,
    CONSTRAINT fk_alerts_truck FOREIGN KEY (truck_id)
        REFERENCES trucks(truck_id) ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT fk_alerts_shipment FOREIGN KEY (shipment_id)
        REFERENCES shipments(shipment_id) ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT fk_alerts_dock FOREIGN KEY (dock_id)
        REFERENCES dock_doors(dock_id) ON UPDATE CASCADE ON DELETE SET NULL
);

-- Helpful indexes for common lookups

CREATE INDEX idx_skus_product_id ON skus(product_id);
CREATE INDEX idx_forecast_sku_date ON demand_forecast(sku_id, forecast_date);
CREATE INDEX idx_inventory_sku_location ON inventory(sku_id, location_id);
CREATE INDEX idx_production_sku_date ON production_orders(sku_id, planned_date);
CREATE INDEX idx_shipments_sku ON shipments(sku_id);
CREATE INDEX idx_shipments_arrival ON shipments(planned_arrival);
CREATE INDEX idx_shipments_priority ON shipments(priority);
CREATE INDEX idx_trucks_shipment ON trucks(shipment_id);
CREATE INDEX idx_tracking_truck_timestamp ON truck_tracking(truck_id, timestamp);
CREATE INDEX idx_appointments_arrival ON appointments(scheduled_arrival);
CREATE INDEX idx_dock_assignments_truck ON dock_assignments(truck_id);
CREATE INDEX idx_alerts_status ON alerts(status);
CREATE INDEX idx_alerts_created_at ON alerts(created_at);

COMMIT;
